apiVersion: apps/v1
kind: Deployment
metadata:
  name: worldin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worldin
  template:
    metadata:
      labels:
        app: worldin
    spec:
      containers:
        - name: worldin
          image: worldinacr.azurecr.io/worldindocimage:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: worldin
  labels:
    name: worldin
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: worldin
  type: LoadBalancer