apiVersion: apps/v1
kind: Deployment
metadata:
  name: worldin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worldin
  template:
    metadata:
      labels:
        app: worldin
    spec:
      containers:
        - name: worldin
          image: worldinacr.azurecr.io/worldindocimage:v4
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILE
              value: prod
---
apiVersion: v1
kind: Service
metadata:
  name: worldin
  labels:
    name: worldin
spec:
  loadBalancerIP: <your-public-request-ip>
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: worldin
  type: LoadBalancer